# Generated by Django 3.2.4 on 2021-08-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_todoitem_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.TextField(max_length=32),
        ),
    ]
